name: Pre-commit auto-update

on:
  workflow_call:

jobs:
  auto-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.x

      - run: pip install pre-commit
      - run: pre-commit autoupdate --freeze
      - run: pre-commit run --all-files || true

      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        if: always() && github.event_name != 'pull_request'
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        with:
          commit-message: "style: Update pre-commit hooks"
          branch: update/pre-commit-hooks
          branch-suffix: timestamp
          delete-branch: true
          title: "style: Update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
